### ISSUE TITLE
customer credit is inserted in the middle of the payment methods (see image)

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-ironwool#8]
![screen shot 2016-02-02 at 8 50 35 am](https://cloud.githubusercontent.com/assets/11448089/12757426/dc268922-c98c-11e5-9794-fedcbf969cc4.png)

**Comment by influxweb** [comment]
Due to the way the payments loop works, these results are what is expected. In the release of 9.5, the option to change the payment order was added. Under "Payment Settings", you will see a tab titled "Payment Method Rules". You can edit the priority level of the payment methods; a higher priority will place it higher in the list. Try placing the customer credit method with the lowest priority.
